spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 89bda03a-5624-47dc-b25c-ffad80d7bd80
        credential:
          client-id: 48e5f5e5-601a-4b09-abc6-631c6d60d2ee
          client-secret: TSC8Q~cksa-eIBT5TzCYKpKcWSmawU8EUvDDLahh
        user-group:
          allowed-groups:
            - "Admin"
            - "Researcher"

server:
  port: 9191
  forward-headers-strategy: native
